model_config_name: SeqBatchedBertSpanishBase
bert_model_name: dccuchile/bert-base-spanish-wwm-cased
bert_model_output_dim: 768
num_epochs: 15
save_models_dir: ./models
model_name: SeqLabelerBatched
optimizer: Adam
learning_rate: 1e-5
