model_config_name: BatchedBert
bert_model_name: bert-base-cased
bert_model_output_dim: 768
num_epochs: 15
save_models_dir: ./models
model_name: SeqLabelerBatched
optimizer: Adam
learning_rate: 1e-5
batch_size: 4
