model_config_name: SpanBatchedNoTokenizationBaseSpanish
bert_model_name: dccuchile/bert-base-spanish-wwm-cased
bert_model_output_dim: 768
num_epochs: 15
save_models_dir: ./models
model_name: SpanBertNoTokenizationBatched
optimizer: Adam
learning_rate: 1e-5
batch_size: 4
