model_config_name: SpanBatchedNoTokenizationLargeSpanish
bert_model_name: xlm-roberta-large
bert_model_output_dim: 1024
num_epochs: 15
model_name: SpanBertNoTokenizationBatched
optimizer: Adam
learning_rate: 1e-5
batch_size: 4