model_config_name: SpanBertNounPhrase
bert_model_name: bert-base-cased
bert_model_output_dim: 768
num_epochs: 10
save_models_dir: ./models
model_name: SpanBertNounPhrase
optimizer: Adam
learning_rate: 1e-5
batch_size: 4
