model_config_name: SeqLabelCRF
bert_model_name: bert-base-cased
bert_model_output_dim: 768
num_epochs: 10
save_models_dir: ./models
model_name: JustBert3ClassesCRF
optimizer: Adam
learning_rate: 1e-5
batch_size: 4
