model_config_name: span_rep_width_embed_large_model_config
bert_model_name: xlm-roberta-large
bert_model_output_dim: 1024
num_epochs: 15
save_models_dir: ./models
model_name: SpanBertSpanWidthEmbedding
optimizer: Adam
learning_rate: 1e-5