train_annos_file_path: ./preprocessed_data/multiconer_coarse_train_annos.tsv
valid_annos_file_path: ./preprocessed_data/multiconer_coarse_valid_annos.tsv
train_tokens_file_path: ./preprocessed_data/multiconer_coarse_train_tokens.json
valid_tokens_file_path: ./preprocessed_data/multiconer_coarse_valid_tokens.json
train_sample_text_data_file_path: ./preprocessed_data/multiconer_coarse_train_sample_text.json
valid_sample_text_data_file_path: ./preprocessed_data/multiconer_coarse_valid_sample_text.json
train_samples_file_path: ./preprocessed_data/multiconer_coarse_train_samples.json 
valid_samples_file_path: ./preprocessed_data/multiconer_coarse_valid_samples.json 
types_file_path: ./preprocessed_data/multiconer_coarse_train_types.txt
num_types: 6
dataset_name: multiconer_coarse
test_tokens_file_path: change_this
test_sample_text_data_file_path: change_this
test_samples_file_path: change_this
dataset_config_name: multiconer_coarse_vanilla