train_samples_file_path: ./preprocessed_data/living_ner_train_window_combo_production_samples.json
valid_samples_file_path: ./preprocessed_data/living_ner_valid_window_combo_production_samples.json
test_samples_file_path: ./preprocessed_data/living_ner_test_window_combo_production_samples.json
types_file_path: ./preprocessed_data/living_ner_test_window_production_types.txt
num_types: 2
dataset_name: living_ner
dataset_config_name: living_ner_window_combo
expected_number_of_train_samples: nothing
expected_number_of_valid_samples: nothing
expected_number_of_test_samples: nothing
