train_samples_file_path: ./preprocessed_data/social_dis_ner_train_vanilla_samples.json
valid_samples_file_path: ./preprocessed_data/social_dis_ner_valid_vanilla_samples.json
test_samples_file_path: change_this
types_file_path: ./preprocessed_data/social_dis_ner_train_vanilla_types.txt
num_types: 1
dataset_name: social_dis_ner
dataset_config_name: social_dis_ner_vanilla