train_samples_file_path: ./preprocessed_data/multiconer_fine_train_vanilla_production_samples.json
valid_samples_file_path: ./preprocessed_data/multiconer_fine_valid_vanilla_production_samples.json
test_samples_file_path: ./preprocessed_data/multiconer_fine_test_vanilla_production_samples.json
types_file_path: ./preprocessed_data/multiconer_fine_train_vanilla_production_types.txt
num_types: 33
dataset_name: multiconer_fine
dataset_config_name: multiconer_fine_vanilla
