train_samples_file_path: ./preprocessed_data/social_dis_ner_train_config_socialdisner_vanilla_chatgpt_external_production_samples.json
valid_samples_file_path: ./preprocessed_data/social_dis_ner_valid_config_socialdisner_vanilla_chatgpt_external_production_samples.json
test_samples_file_path: ./preprocessed_data/social_dis_ner_test_config_socialdisner_vanilla_chatgpt_external_production_samples.json
types_file_path: ./preprocessed_data/social_dis_ner_train_chat_gpt_production_types.txt
num_types: 1
dataset_name: social_dis_ner
dataset_config_name: social_dis_ner_external_chatgpt
