train_samples_file_path: ./preprocessed_data/social_dis_ner_train_vanilla_combo_production_samples.json
valid_samples_file_path: ./preprocessed_data/social_dis_ner_valid_vanilla_combo_production_samples.json
test_samples_file_path: ./preprocessed_data/social_dis_ner_test_vanilla_combo_production_samples.json
types_file_path: ./preprocessed_data/social_dis_ner_train_vanilla_types.txt
num_types: 1
dataset_name: social_dis_ner
dataset_config_name: social_dis_ner_vanilla_combo
expected_number_of_train_samples: nothing
expected_number_of_valid_samples: nothing
expected_number_of_test_samples: nothing
