train_samples_file_path: ./preprocessed_data/legaleval_preamble_train_vanilla_samples.json
valid_samples_file_path: ./preprocessed_data/legaleval_preamble_valid_vanilla_samples.json
test_samples_file_path: change_this
types_file_path: ./preprocessed_data/legaleval_preamble_train_vanilla_types.txt
num_types: 14
dataset_name: legaleval_preamble
