train_annos_file_path: ./preprocessed_data/legaleval_train_judgement_annos.tsv
valid_annos_file_path: ./preprocessed_data/legaleval_valid_judgement_annos.tsv
train_tokens_file_path: ./preprocessed_data/legaleval_train_judgement_tokens.json
valid_tokens_file_path: ./preprocessed_data/legaleval_valid_judgement_tokens.json
train_sample_text_data_file_path: ./preprocessed_data/legaleval_train_judgement_sample_text.json
valid_sample_text_data_file_path: ./preprocessed_data/legaleval_valid_judgement_sample_text.json
train_samples_file_path: ./preprocessed_data/legaleval_train_judgement_samples.json 
valid_samples_file_path: ./preprocessed_data/legaleval_valid_judgement_samples.json 
types_file_path: ./preprocessed_data/legaleval_train_judgement_types.txt
num_types: 14
dataset_name: legaleval_judgement
test_tokens_file_path: change_this
test_sample_text_data_file_path: change_this
test_samples_file_path: change_this