train_samples_file_path: ./preprocessed_data/genia_train_vanilla_samples.json
valid_samples_file_path: ./preprocessed_data/genia_valid_vanilla_samples.json
test_samples_file_path: change_this
types_file_path: ./preprocessed_data/genia_train_vanilla_types.txt
num_types: 1
dataset_name: social_dis_ner
